### ISSUE TITLE
Support for short version syntax

### ISSUE THREAD

**Issue by solnic** [eregon/use-ruby-action#1]
It would be very helpful if this action supported short version syntax too, examples:

- `ruby-2.6`
- `jruby-9.2.9`
- `truffleruby-19.3`

**Comment by eregon** [comment]
Indeed, that should be easy because there is a list of versions at https://github.com/eregon/ruby-install-builder/blob/metadata/versions.json
I'll try to implement it today.

**Comment by eregon** [comment]
I implemented it in https://github.com/eregon/use-ruby-action/pull/2 and updated the README.
