### ISSUE TITLE
Fix "Insecure world writable dir ... in PATH" warnings

### ISSUE THREAD

**Issue by eregon** [eregon/use-ruby-action#16]
Reported by @benoittgt

This is the same as https://github.com/actions/virtual-environments/issues/267 but meant to track how to solve it for this action.

To fix it (at least for now), I'll rebuild all MRI releases with `CPPFLAGS="-DENABLE_PATH_CHECK=0" ./configure ...` as mentioned in https://github.com/actions/virtual-environments/issues/267#issuecomment-581145369

**Comment by eregon** [comment]
Fixed and released as https://github.com/eregon/use-ruby-action/releases/tag/v1.12.2

**Comment by benoittgt** [comment]
Thanks!
