### ISSUE TITLE
Fails to install ruby 2.3

### ISSUE THREAD

**Issue by solnic** [eregon/use-ruby-action#3]
I'm getting the following error:

```
Run actions/setup-ruby@v1
2  with:
3   ruby-version: 2.3
4 ##[error]Version 2.3 not found
5 ##[error]Node run failed with exit code 1
```

**Comment by eregon** [comment]
Ruby 2.3 is not supported currently (or not yet).
Do you need it for testing some gem which still supports 2.3?

FWIW, Ruby 2.3 is [end-of-life](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/) and IIRC does not support any recent OpenSSL, but I can give it a try to build it in https://github.com/eregon/ruby-install-builder

**Comment by eregon** [comment]
BTW, this is actually an error message from [actions/setup-ruby](https://github.com/actions/setup-ruby), not from this action.

**Comment by eregon** [comment]
FWIW, the error message of this action for `2.3` is:
```
Run ./
  with:
    ruby-version: 2.3
##[error]Unknown version 2.3 (2.3)
##[error]Node run failed with exit code 1
```
We could probably make that better.

**Comment by eregon** [comment]
I improved the error message in 7d189e207591e494b567ff16f6c727d32a1ce2d3:
https://github.com/eregon/use-ruby-action/runs/373716540
```
##[error]Unknown version 2.3 for ruby
        input: 2.3
        available versions for ruby: 2.4.9, 2.5.7, 2.6.5, 2.7.0
        File an issue at https://github.com/eregon/ruby-install-builder/issues if would like support for a new version
##[error]Node run failed with exit code 1
```

**Comment by eregon** [comment]
I tried in https://github.com/eregon/ruby-install-builder/runs/373803355 but it's a mess:
* Homebrew no longer has an `openssl@1.0` formula
* ubuntu-16.04 runners have openssl 1.1 and apparently no way to install openssl 1.0
* ubuntu-18.04 can install openssl 1.0 with `apt-get install -y libssl1.0-dev`

So it's not looking good so far.

I think it's time to say goodbye to Ruby 2.3. It can only be run insecurely at this point and no longer builds on any recent OS or with any supported OpenSSL version.

**Comment by solnic** [comment]
> Do you need it for testing some gem which still supports 2.3?

Yes, unfortunately, but I think we can actually drop it. I gotta talk to other core team folks about it.

**Comment by eregon** [comment]
Thanks, please tell me the result.

I'm looking to use `ruby-build` which might help as it builds its own openssl, but currently only on macOS (`--if has_broken_mac_openssl` in https://github.com/rbenv/ruby-build/blob/bac1f1cae63cea697ca8d63b167e0bd7587295ee/share/ruby-build/2.3.8#L1). It seems possible to make it build old openssl versions as well on Linux, I'll try that.

**Comment by eregon** [comment]
I managed to get builds of Ruby 2.3 working with `ruby-build` and making `ruby-build` build its own OpenSSL on Ubuntu too.

I mentioned this in the README:
> Note that Ruby 2.3 and the OpenSSL version it needs (1.0.2) are both end-of-life, which means Ruby 2.3 is unmaintained and considered insecure.

But if you need to use Ruby 2.3, it should work as good as any other build of Ruby 2.3.
