### ISSUE TITLE
HTTP 404 when attempting to install Ruby on windows-latest

### ISSUE THREAD

**Issue by matchai** [eregon/use-ruby-action#9]
Excellent work on use-ruby-action! 🙏 

When using the action on Windows, it looks like it may not be correctly performing Windows-specific actions to download Ruby from RubyInstaller. Instead, it 404s, attempting to download the binary from `ruby-install-builder`.

Here is an example run where the failure is encountered:
https://github.com/starship/starship/runs/395744542

**Comment by eregon** [comment]
The problem is the `v1` tag is older, could you use `- uses: eregon/use-ruby-action@master` as documented in the README?

Maybe I should update the tag as the `actions` actions do:
https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations

But updating a tag still sounds hacky to me, I'm unsure if it's a good idea.

**Comment by matchai** [comment]
As a consumer, having actions use semver gives me confidence that the API won't make breaking changes overnight.

**Comment by eregon** [comment]
Right. Would you be fine with a moving `v1` tag then?
Or you'd want to use the full version tag like `v1.1.0` (but then not any bug fixes / compatible improvements)?

I guess making `v1` a branch would make sense actually, that way it can be moved cleanly in `git`.
But it might be a bit surprising with `v1.1.0` being a tag.

**Comment by eregon** [comment]
I created releases and a `v1` branch. I also documented the versioning strategy in the README.

Thank you for filing the issue.
I believe that should fix this issue, here is a run for 2.7.0 on WIndows using `v1`: https://github.com/eregon/use-ruby-action/runs/396007303

**Comment by matchai** [comment]
I'd be happy to use a moving `v1` tag. Thank you for the quick update. 🙏😊
